### ISSUE TITLE
Tasks for next week - please add to this I didn't get to finish it on friday

### ISSUE THREAD

**Issue by jo-hall** [j-fletcher/barc_blanket#20]
We are in the home stretch for this project 

- Calculations of TBR, Heating, and Dose for the following cases:
     -  Pure fusion operation (no waste)
     - 1, 5, 10% waste fraction from the mix of all tanks

- Blanket Composition after coupled depletion
    - Deliverables: Plots of Activity vs. Time, Nuclide Masses Vs. Time, Time to Class-C threshold
    - Need to do this for at least
        - The most active tank
        - Mix of all tanks (average)
        - All tanks mix with U238, Th232 taken out
        - All tanks mix with U and Pu taken out
**In order to do this**, we need to:
- Cross sections: need to use endf-8 cross section plus the exotic ones from Jack :), add these to the .xml file, and use the endf-8 fast neutron chain file, which also needs to be updated.

**Comment by j-fletcher** [comment]
It doesn't seem realistic to just take out Th232/U238--see new list of materials in slack
